#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/config

if ! [ -f "$QUERY" ];
then
  echo "SPARQL Query file not found."
  exit 0
fi
echo

REQUESTS=$(($REQUESTS - 1))
COUNT=0

function url_encode() {
    echo "$1" \
    | sed \
        -e 's/%/%25/g' \
        -e 's/ /%20/g' \
        -e 's/!/%21/g' \
        -e 's/"/%22/g' \
        -e "s/'/%27/g" \
        -e 's/#/%23/g' \
        -e 's/(/%28/g' \
        -e 's/)/%29/g' \
        -e 's/+/%2b/g' \
        -e 's/,/%2c/g' \
        -e 's/-/%2d/g' \
        -e 's/:/%3a/g' \
        -e 's/;/%3b/g' \
        -e 's/?/%3f/g' \
        -e 's/@/%40/g' \
        -e 's/\$/%24/g' \
        -e 's/\&/%26/g' \
        -e 's/\*/%2a/g' \
        -e 's/\./%2e/g' \
        -e 's/\//%2f/g' \
        -e 's/\[/%5b/g' \
        -e 's/\\/%5c/g' \
        -e 's/\]/%5d/g' \
        -e 's/\^/%5e/g' \
        -e 's/_/%5f/g' \
        -e 's/`/%60/g' \
        -e 's/{/%7b/g' \
        -e 's/|/%7c/g' \
        -e 's/}/%7d/g' \
        -e 's/~/%7e/g'
}


echo ""
URISFILE="data/uris.csv"
while IFS=',' read uri label ; do

    if [[ "$uri" == "s" ]];
    then
        continue
    fi

    if [[ "$QUERY" == *"unknown-relations"* ]];
    then
        label=$(echo $label | sed 's/"//g')
        label=$(echo $label | sed 's/\r//g')
        echo "$uri -- $label"
        curl $AUTHMETHOD --user "$MLUSER:$MLPASS" -X POST \
            --data-urlencode query@$QUERY \
            --data-urlencode "database=$DB" \
            --data-urlencode "bind:resource_uri=$uri" \
            --data-urlencode "bind:resource_label@en=$label" \
            -H "Content-type: application/x-www-form-urlencoded" \
            -H "Accept: application/sparql-results+xml" \
            http://$MLHOST:$MLPORT/v1/graphs/sparql

    elif [[ "$QUERY" == *"known-relations"* || "$QUERY" == *"simple_select"* ]];
    then
        echo "$uri"
        curl -s $AUTHMETHOD --user "$MLUSER:$MLPASS" -X POST \
            --data-binary @$QUERY \
            -H "Content-type: application/sparql-query" \
            -H "Accept: application/sparql-results+xml" \
            "http://$MLHOST:$MLPORT/v1/graphs/sparql?database=$DB&bind:resource_uri=$uri"
    fi

    COUNT=$(($COUNT + 1))
    if [ "$COUNT" -gt "$REQUESTS" ]
    then
        break
    fi
    
done < $URISFILE
